-- ============================================================================
-- NOT EXECUTED. Neither statement in this file has been run against any
-- database. It exists so the owner has something concrete to approve.
--
-- Read the ordering section first. The two statements below are steps 1 and 3
-- of three, and step 2 is a code deploy. Running them out of order, or running
-- both at once, silently corrupts any post written in between.
-- ============================================================================
--
-- Purpose: convert blogs.date from TIMESTAMP WITHOUT TIME ZONE to TIMESTAMPTZ,
-- recovering the instant each existing value was meant to denote, and move
-- responsibility for the value from the application to the column.
--
-- ---------------------------------------------------------------------------
-- Measured facts this file depends on
-- ---------------------------------------------------------------------------
-- Read from the live database, aggregates only:
--
--   column      timestamp without time zone, precision 6, NOT NULL, no default
--   session     TimeZone GMT, DateStyle ISO, MDY
--   rows        6 total, 2 at 00:00:00, span 2025-2026
--   ambiguous   0 rows fall in a DST fall-back hour or spring-forward gap
--
-- And the coercions, measured with literal SELECTs that read no table:
--
--   NOW()::timestamp                              -> 17:47  (GMT wall-clock)
--   (NOW() AT TIME ZONE 'America/Denver')::text    -> 11:47  (Denver wall-clock)
--   '22:30'::timestamp::timestamptz                -> 22:30+00
--   '22:30'::timestamp AT TIME ZONE 'America/...'  -> 04:30+00
--
-- The first two lines are the whole reason this is a three-step migration.
--
-- ---------------------------------------------------------------------------
-- Why the obvious one-liner is wrong
-- ---------------------------------------------------------------------------
-- A bare
--
--   ALTER TABLE blogs ALTER COLUMN date TYPE TIMESTAMPTZ;
--
-- casts using the *session* TimeZone, which is GMT here. Every stored value is
-- Denver wall-clock, so each would be reinterpreted as if it had been UTC and
-- land 6-7 hours from the instant it meant. That conversion is mechanically
-- reversible -- `date AT TIME ZONE 'GMT'` inverts it exactly -- so it does not
-- destroy anything; it just produces the wrong answer, and does so without a
-- warning. The USING clause in step 3 is what makes it the right answer.
--
-- ---------------------------------------------------------------------------
-- ORDERING -- the part that matters
-- ---------------------------------------------------------------------------
-- The schema change and the code change cannot be atomic: one is a DDL
-- statement and the other is a deploy. So the question is what a post written
-- between them records, and the answer has to be "the right thing" for every
-- pairing, because a wrong answer here is silent and permanent.
--
--   STEP 1  (this file, below)   SET DEFAULT (now() AT TIME ZONE 'America/Denver')
--
--     A naive default for the naive column, giving Denver wall-clock -- the
--     same convention every existing row already follows, and the convention
--     step 3's USING clause assumes. Safe under the OLD code, which names
--     `date` explicitly and so never reaches the default. Safe under the NEW
--     code, which omits it.
--
--   STEP 2  deploy the application code
--
--     createBlog stops naming `date` at all, so the default supplies it. Both
--     render sites pin `timeZone: 'America/Denver'`.
--
--     This step has the one unavoidable window, and it is display-only: until
--     step 3 runs, a naive value is still parsed in the process's zone (UTC on
--     Vercel) and now formatted in Denver, so dates read 6-7 hours early and an
--     early-morning post may show the previous day. No stored value is affected
--     and step 3 corrects the display. Minutes of exposure on a 6-row blog.
--
--   STEP 3  (this file, below)   ALTER TYPE ... USING ..., then SET DEFAULT now()
--
--     One transaction, so the type and its default can never disagree.
--
-- What NOT to do, and why:
--
--   * Do not put `NOW()` in the INSERT and deploy before step 3. NOW() is a
--     timestamptz; a naive column coerces it through the session zone, storing
--     GMT wall-clock (17:47 above, not 11:47). Step 3 would then read that as
--     Denver and shift it a further 6-7 hours. Permanent, silent, and it
--     survives the rollback.
--   * Do not run step 3 before step 2. The old code sends a Denver wall-clock
--     *string*, which a timestamptz column parses using the session zone, GMT.
--     Same corruption, opposite direction.
--   * Do not collapse steps 1 and 3. Between them the column must be naive with
--     a naive default, or a post written in the deploy window has no correct
--     value available to it.
--
-- If a post IS written during step 2's window, nothing is wrong with it. If one
-- is written between step 2 and step 1, the INSERT fails outright with a
-- not-null violation -- loud, and recoverable by resubmitting.
--
-- ---------------------------------------------------------------------------
-- What the USING clause assumes about existing rows
-- ---------------------------------------------------------------------------
-- That every existing naive value is Denver wall-clock. True for anything
-- written through createBlog. Two caveats, both measured:
--
--   * 2 of the 6 rows sit at 00:00:00. They came from the seed list into what
--     was then a DATE column, so they denote a calendar day with no time of day
--     at all. "Midnight in Denver" is a choice imposed on them rather than a
--     fact recovered -- benign, because it displays as the same calendar day,
--     which is what a date-only post means.
--   * A row inserted by hand from a machine in another zone would be shifted by
--     the difference, undetectably, because the intended zone was never
--     recorded. That is the underlying disease. This migration cannot cure rows
--     that already have it, and there is no evidence any row does.
--
-- DST ambiguity would be the third caveat -- `naive AT TIME ZONE` is ambiguous
-- inside the autumn fall-back hour and undefined inside the spring-forward gap,
-- and Postgres resolves both silently. MEASURED AT ZERO ROWS, so it does not
-- apply. Note that a round-trip test does not detect this: an ambiguous autumn
-- value round-trips cleanly through both directions. The query at the bottom
-- tests local linearity instead.
--
-- ---------------------------------------------------------------------------
-- Locking and reversal
-- ---------------------------------------------------------------------------
-- ALTER COLUMN ... TYPE with a USING clause rewrites the table under an ACCESS
-- EXCLUSIVE lock. Instant at 6 rows; the note matters only if this is ever run
-- against a much larger table.
--
-- Step 3 reverses exactly for every row that satisfied the assumption above:
--
--   BEGIN;
--   ALTER TABLE blogs ALTER COLUMN date DROP DEFAULT;
--   ALTER TABLE blogs
--     ALTER COLUMN date TYPE TIMESTAMP WITHOUT TIME ZONE
--     USING date AT TIME ZONE 'America/Denver';
--   ALTER TABLE blogs
--     ALTER COLUMN date SET DEFAULT (now() AT TIME ZONE 'America/Denver');
--   COMMIT;
--
-- For a row that did NOT satisfy it, the rollback is worse than useless: a
-- wrongly-guessed instant round-trips back to the identical naive value it
-- started as, so the rollback hides the damage rather than revealing it. Take a
-- backup before step 3 regardless of how small the table is.


-- ###########################################################################
-- STEP 1 -- run before deploying the code. Safe under old and new code alike.
-- ###########################################################################

ALTER TABLE blogs
  ALTER COLUMN date SET DEFAULT (now() AT TIME ZONE 'America/Denver');


-- ###########################################################################
-- STEP 3 -- run only AFTER the code deploy is live. Take a backup first.
-- ###########################################################################

BEGIN;

ALTER TABLE blogs
  ALTER COLUMN date TYPE TIMESTAMPTZ
  USING date AT TIME ZONE 'America/Denver';

-- In the same transaction as the type change, so the column and its default can
-- never briefly disagree about what a value means.
ALTER TABLE blogs
  ALTER COLUMN date SET DEFAULT now();

COMMIT;


-- ---------------------------------------------------------------------------
-- Verification. These are SELECTs and change nothing. Already run; the results
-- are recorded above. Left commented out so this file cannot be executed whole
-- without a decision.
-- ---------------------------------------------------------------------------
--
-- Rows carrying no real time of day (probable seed rows) -- measured 2 of 6:
--
--   SELECT count(*) FILTER (WHERE date::time = '00:00:00') AS midnight_rows,
--          count(*)                                       AS total_rows
--   FROM blogs;
--
-- Rows whose naive value is ambiguous or nonexistent in America/Denver --
-- measured 0. Away from a transition, shifting the naive input by an hour must
-- shift the resulting instant by exactly an hour; that breaks in the
-- neighbourhood of an offset change in either direction:
--
--   SELECT id, date
--   FROM blogs
--   WHERE ((date + interval '1 hour') AT TIME ZONE 'America/Denver')
--           - (date AT TIME ZONE 'America/Denver') <> interval '1 hour'
--      OR (date AT TIME ZONE 'America/Denver')
--           - ((date - interval '1 hour') AT TIME ZONE 'America/Denver')
--           <> interval '1 hour';
--
-- Span of stored values, to check nothing sits far from when the posts were
-- written -- measured 2025-2026:
--
--   SELECT min(date) AS earliest, max(date) AS latest FROM blogs;
--
-- After step 3, that the default is an instant and not a wall-clock reading:
--
--   SELECT column_default, data_type
--   FROM information_schema.columns
--   WHERE table_name = 'blogs' AND column_name = 'date';
